#!/bin/bash

sudo yum -y update

# Install Amazon ssm Agent 
cd /tmp
curl https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm -o amazon-ssm-agent.rpm
yum install -y amazon-ssm-agent.rpm


# install java 11
sudo amazon-linux-extras install java-openjdk11 -y;

# Install docker
sudo yum install docker -y
sudo systemctl enable --now docker

sudo usermod -a -G docker ec2-user


