pipeline {
    agent any
    stages {
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }
        stage('Code Build') {
            steps {
                echo 'Running maven build'
                sh 'mvn clean install -DskipTests'
            }
        }
    }
}