pipeline {
    agent any
    stages {
        // stage('Checkout repo') {
        //     steps {
        //         git branch: 'main',
        //         credentialsId: 'jenkins-git',
        //         url: 'https://github.com/hernanku/bookstore-web-app.git'
        //     }
        // }
        stage('Build app') {
            agent {
                docker { image 'maven:3.8.6-openjdk-8' }
            }
            steps {
                sh """
                cd Bookstore && \
                mvn clean install -DskipTests
                """
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: true,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true
            )
        }
    }
}




// pipeline {
//     agent any
//     stages {
//         stage('Chekout code') {
//             steps {
//                 script {
//                     git branch: "main", 
//                     credentialsId: 'jenkins-git-token',
//                     url: 'https://github.com/hernanku/bookstore-web-app.git'
//                 }
//             }
//         }
//         stage('Build code') {
//             steps {
//                 script {
//                     docker.image('maven:3.8.6-openjdk-8').inside {
//                         sh "mvn clean package -DskipTests"

//                     }
//                 }
//             }
//         }
//     }
// }


